# # # # # # # # # # # # # # # # #
#
#  Welcome to DecentMenus config.yml.
#
# # # # # # # # # #

defaults:
  menu-title: 'Unnamed Menu'



# # # # # # # # # # # # # # # # #
#
#  Pinger
#
#   - Setup servers, that will automatically be pinged by the plugin
#   making it available to use built-in placeholders in order to display
#   information about them like online players or status.
#
# # # # # # # # # #

pinger:
  enabled: true
  # Update interval in ticks (20 ticks = 1 second)
  update-interval: 20
  # Format: <name>:<ip>:<port>
  servers:
    - 'Survival:127.0.0.1:25565'
    - 'Lobby-01:127.0.0.1:25566'



# # # # # # # # # # # # # # # # #
#
#  Messages
#
#   - You can edit any message here
#
# # # # # # # # # #

messages:
  # Use '{prefix}' in other messages, and it will be replaced with this.
  prefix: '&8[&3DecentMenus&8] &7'
  usage: '{prefix}Use: &b/dm <args> &7or &b/openmenu <menu>.'
  no-perm: '{prefix}&cYou are not allowed to do this.'
  unknown-sub-command: '{prefix}&cUnknown sub command.'
  menu-no-perm: '{prefix}You cannot open that menu.'
  menu-usage: '{prefix}Usage: &b/decentmenus <list|ver>'
  menu-open-usage: '{prefix}Usage: &b/openmenu <menu>'
  menu-does-not-exist: '{prefix}Menu called ''%s'' doesn''t exist.'
  menu-list: '{prefix}Menus: &b%s'